GET http://localhost:3321/fotosInstagram

###
GET http://localhost:3321/dadosMongoDb


###
PUT http://localhost:3321/fotosInstagram/:id
Content-Type: application/json

{
    "title": "Kit de dias dos pais",
    "description": "sistema pegue e monte",
    "value": 160,
    "category": "painel"
}


###
POST http://localhost:3321/postFotos/